### ISSUE TITLE
Need add video option to driver capbilities to use HW jpeg decoding

### ISSUE THREAD

**Issue by st7109** [lambdal/lambda-stack-dockerfiles#14]
To maintianer, 
I want to use video, and need change "ENV NVIDIA_DRIVER_CAPABILITIES compute,utility" to  "ENV NVIDIA_DRIVER_CAPABILITIES compute,utility,video" 。any other advice? please don't hesitate let me know. thanks.

**Comment by sclarkson** [comment]
Very late reply, but in case anyone else still needs this

The settings there are intended to be a decent default. If you want additional driver capabilities in your container, you can either modify the Dockerfile or specify them at runtime, as described below.

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#driver-capabilities
