### ISSUE TITLE
/libnvidia-ml.so.1: file exists: unknown

### ISSUE THREAD

**Issue by shortwavedave** [lambdal/lambda-stack-dockerfiles#15]
Hello,

trying to run the latest Jammy image produces the following error

> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
> nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/40c7fccee0aa8659243a8180389b333c9a6b85fac895a95207bfddca46df4fc6/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.

I think this is related to the issue solved by adding the libnvidia-ml1 line here:
https://github.com/lambdal/lambda-stack-dockerfiles/blob/567632657daf3a7e3d6e0ba7d63234ec5ca776b3/control#L27

however I don't understand how that fix works, otherwise I would modify it. Could anyone explain what that does and if it applies to the error above?

**Comment by sclarkson** [comment]
Should be resolved with 8f87f683610523701f5a5ffc59dfd055650df3df. This can happen when the CUDA toolkit version in the repo gets out of sync with what is in the Dockerfiles here. I'll try to update more quickly with the next CUDA toolkit release.
