### ISSUE TITLE
Dockerfile.jammy error

### ISSUE THREAD

**Issue by gggjerry** [lambdal/lambda-stack-dockerfiles#16]
Dear Sir, 

I run into error when trying to build a docker image from the HOME directory of my tensor book UBUNTU 22. The 6th line of the code: ADD control . 
is where i am running into error. 
Please kindly advise. 

See below: 

(base) gerry@gerry-TensorBook-2022:~$ sudo docker build -t lambda-stack:22.04 -f Dockerfile.jammy .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon   29.7GB
Step 1/9 : FROM ubuntu:22.04
 ---> 8a3cdc4d1ad3
Step 2/9 : WORKDIR /root/
 ---> Using cache
 ---> 2113d17b9912
Step 3/9 : ADD control .
ADD failed: file not found in build context or excluded by .dockerignore: stat control: file does not exist

**Comment by sclarkson** [comment]
It sounds like you copied the Dockerfile from the repository, but not the corresponding control file (or GPG key). In the future, just build it from the repository directory.
