### ISSUE TITLE
Help with use of the docker image

### ISSUE THREAD

**Issue by scepeda78** [lambdal/lambda-stack-dockerfiles#2]
Dear all, I was able to create the image of the docker, but when runing the container, i cannot see the nvidia card from the docker image. I cannot run the tensor flow since none of the nvida controlers are present in the docker.
Do you have a tutorial about how to use the docker with ubuntu 18.04?

**Comment by sclarkson** [comment]
Are you using [nvidia-docker](https://github.com/NVIDIA/nvidia-docker)?

**Comment by sclarkson** [comment]
Setup instructions added in 79f3879
