### ISSUE TITLE
Ubuntu 18.04 docker image not building successfully

### ISSUE THREAD

**Issue by amitpandey2194** [lambdal/lambda-stack-dockerfiles#5]
Mine is 18.04 as well, but it didn't work for me. I tried the #3 with creating the 99fixbadproxy file and 
copying the pull request in #3 but it still gave me the following error:
E: Failed to fetch http://archive.lambdalabs.com/ubuntu/pool/main/n/nvidia-cuda-toolkit/libnppif10.0_10.0.130-0lambda3_amd64.deb  Undetermined Error [IP: 54.231.168.163 80]
E: Failed to fetch http://archive.lambdalabs.com/ubuntu/pool/main/n/nvidia-cudnn/libcudnn-dev_7.5.1-0lambda1_amd64.deb  Undetermined Error [IP: 54.231.168.163 80]
E: Failed to fetch http://archive.lambdalabs.com/ubuntu/pool/main/n/nvidia-cuda-toolkit-9.0/libaccinj64-9.0_9.0.176.4-0lambda1_amd64.deb  Undetermined Error [IP: 54.231.168.163 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
I am behind companies proxy. Anything else that I can try @jenkinsadmin

**Comment by avnf** [comment]
Support for bionic 18.04 was removed in https://github.com/lambdal/lambda-stack-dockerfiles/commit/461d601d16e4a32915cb3bd4aecb67d0bae9f95e
