### ISSUE TITLE
Question about RTX 2070 Super support on Lambda Stack

### ISSUE THREAD

**Issue by arturbecker** [lambdal/lambda-stack-dockerfiles#6]
Hey all,
I know you don't have any good reason to support configurations that you don't sell, but I'm wondering if there's anyway I can make Lambda Stack work with newer nvidia drivers.
See my problem is that the 418.88 version it currently uses does not support my RTX 2070 Super. Therefore, the graphic interface fails to start, and e.g. nvidia-smi on a root shell does not recognize my card.
Drivers 430 and up do support it, though. Any ideas if I could manage to update the drivers without breaking everything else?

**Comment by sclarkson** [comment]
We will switch to the 440 series in the near future.

You can install from Ubuntu's PPA in the meantime. 

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by sclarkson** [comment]
The 440 series driver is now in Lambda Stack
