### ISSUE TITLE
dpkg: error: cannot access archive 'libcuda1-dummy_10.0_all.deb': No such file or directory

### ISSUE THREAD

**Issue by maisonhai3** [lambdal/lambda-stack-dockerfiles#7]
I am following the step 2 in this guide: https://lambdalabs.com/blog/set-up-a-tensorflow-gpu-docker-container-using-lambda-stack-dockerfile/ with codes:
`sudo docker build -t lambda-stack -f Dockerfile.$(lsb_release -cs) git://github.com/lambdal/lambda-stack-dockerfiles.git`

My terminal output an error of libcuda1-dummy_10.0_all.deb:

```
dpkg-deb: building package 'libcuda1-dummy' in '../libcuda1-dummy_10.2_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!

dpkg: error: cannot access archive 'libcuda1-dummy_10.0_all.deb': No such file or directory
```

Then I tracked your code and see below lines in In Dockerfile.bionic.
```
RUN apt-get update && \
	apt-get install --yes equivs && \
	equivs-build control && \
	dpkg -i libcuda1-dummy_10.0_all.deb && \
```
There is a conflict: 10.0 in the code vs 10.2 in what actually building.

This stuck me from continuing steps.

**Comment by sclarkson** [comment]
Thanks for the report. Fixed in 3dfc3f3
